/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AlertsNotifier": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthorizerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "authLinks": {
      "MyAuth": string
      "redirect": string
      "type": "sst.sst.Linkable"
    }
    "blogs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "projects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "subscribers": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}